baseURL = "https://example.com"
title = "Your title"
themesDir = "../.."
theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "John Doe"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "brand-x"
    name = "X"
    url = "https://twitter.com/gohugoio"
  [[params.social]]
    icon = "brand-mastodon"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"

  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"
